Assignment 3
kubraa16/assignment-1 pull request #2
Opened 2024-11-22 05:27 UTC by kubraa16

2024-11-22 07:49 UTC, gauravvolopay commented
<img width="238" alt="image" src="https://github.com/user-attachments/assets/12e7aa1b-a331-453b-aaa9-73fb2a16c923">


Make it like 

components 
   core (Inside this we put the components which are dumb in behaviour and can be reused)
      Table 
          CustomCell
          CustomRow
          StocksTable -> rename it to index.js and use it

2024-11-22 09:52 UTC, gauravvolopay requested changes

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/IncomeChart.jsx
> +import { Chart } from "chart.js/auto";
If Chart component is not getting used then remove it, and uninstall the package

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/IncomeChart.jsx
> +  console.log(incomeDetails);
Remove console

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/IncomeChart.jsx
> +  console.log(selectedData);
Remove console

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/CompanyDetails.jsx
> +  // if (error) return <h1>Error: {error}</h1>;
Remove the comment if not required in the the component for use.

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/CompanyDetails.jsx
> +  // const { companyData, loading, error } = useSelector(
Remove the comment if not required in the the component for use.

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/CompanyDetails.jsx
> +          <div className="font-bold text-2xl text-black text-left py-5">
Inorder to avoid repetition could have created a config for displaying the following things 

const Details = [
 { preText:"",  postLabel: companyData[ticker]?.Industry},
 {preText:"Industry", postLabel: companyData[ticker]?.Industry }
]

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/CompanyDetails.jsx
> +              {companyData[ticker]?.SharesOutstanding}
Define a const variable for **companyData[ticker]** so that you would not have to use the same for every use case again and again

2024-11-22 09:52 UTC, gauravvolopay commented on src/App.jsx
> +  // const { topGainers, topLosers, loading, error } = useSelector(
If not important then remove the commented code

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/CustomRow.jsx
> +                    key={colIndex}
Use unique identifier for the **key** prop, as for each row the column indexes will be same, use something like **`${rowIndex}${colIndex}`**

2024-11-22 09:52 UTC, gauravvolopay commented on src/components/IncomeChart.jsx
> +    data.totalRevenue === "None" || data.totalRevenue === null
**["None",null].includes(data?.totalRevenue) ? 0 : data.totalRevenue** is much suitable here.

2024-11-22 10:50 UTC, kubraa16 commented on src/components/IncomeChart.jsx
> +import { Chart } from "chart.js/auto";
In order to get everything imported Im importing chart component.

2024-11-22 10:51 UTC, kubraa16 commented on src/components/CompanyDetails.jsx
> +          <div className="font-bold text-2xl text-black text-left py-5">
created a dump components to show details. Let me know what you think .

2024-11-22 10:51 UTC, kubraa16 commented on src/components/CompanyDetails.jsx
> +              {companyData[ticker]?.SharesOutstanding}
Done.

2024-11-22 10:51 UTC, kubraa16 commented on src/App.jsx
> +  // const { topGainers, topLosers, loading, error } = useSelector(
Done.

2024-11-22 10:52 UTC, kubraa16 commented on src/components/IncomeChart.jsx
> +    data.totalRevenue === "None" || data.totalRevenue === null
Done.

2024-11-22 10:52 UTC, kubraa16 commented on src/components/CompanyDetails.jsx
> +  // const { companyData, loading, error } = useSelector(
Done.

2024-11-22 10:52 UTC, kubraa16 commented on src/components/CompanyDetails.jsx
> +  // if (error) return <h1>Error: {error}</h1>;
Done.

2024-11-22 10:52 UTC, kubraa16 commented on src/components/IncomeChart.jsx
> +  console.log(selectedData);
Done.

2024-11-22 11:07 UTC, kubraa16 commented on src/components/CustomRow.jsx
> +                    key={colIndex}
Done

2024-11-25 04:48 UTC, gauravvolopay approved these changes

2024-11-25 04:59 UTC, merged