Added add new product functionality and update the product details
kubraa16/assignment-1 pull request #5
Opened 2024-12-02 04:45 UTC by kubraa16

2024-12-02 08:52 UTC, gauravvolopay requested changes

2024-12-02 08:52 UTC, gauravvolopay commented on src/components/core/GenericModal.jsx
> +
Make the modal a dumb component, this modal cannot be reused if required showing any other content for some other purpose.

2024-12-06 05:33 UTC, gauravvolopay approved these changes

2024-12-06 05:34 UTC, kubraa16 commented on src/components/core/GenericModal.jsx
> +
Resolved.

2024-12-06 05:39 UTC, merged